# Generated by Django 6.0.6 on 2026-07-04 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('TASK_ASSIGNED', 'Task Assigned'), ('COMMENT', 'New Comment'), ('MENTION', 'You were mentioned'), ('TASK_DONE', 'Dependency Completed'), ('MESSAGE', 'New Message')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'indexes': [models.Index(fields=['user', 'read'], name='notificatio_user_id_1f75db_idx'), models.Index(fields=['user', '-created_at'], name='notificatio_user_id_611c58_idx')],
            },
        ),
    ]
