# Generated by Django 6.0.6 on 2026-07-04 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, max_length=1000, null=True)),
                ('resource_type', models.CharField(choices=[('LINK', 'Link'), ('FILE', 'File'), ('DOC', 'Document'), ('REF', 'Reference')], default='LINK', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('file_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'resources',
                'indexes': [models.Index(fields=['user', 'resource_type'], name='resources_user_id_9310ef_idx'), models.Index(fields=['-created_at'], name='resources_created_b3da52_idx')],
            },
        ),
    ]
