# Generated by Django 6.0.6 on 2026-07-01 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('CHECKING', 'Checking'), ('SAVINGS', 'Savings'), ('CREDIT_CARD', 'Credit Card'), ('CASH', 'Cash'), ('INVESTMENT', 'Investment'), ('RECEIVABLE', 'Receivable'), ('PAYABLE', 'Payable')], max_length=20)),
                ('color', models.CharField(default='#6b7280', max_length=20)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'account_categories',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('TRANSFER', 'Transfer')], max_length=20)),
                ('date', models.DateTimeField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance_app.accountcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transactions',
                'indexes': [models.Index(fields=['user'], name='transaction_user_id_b5bcfd_idx'), models.Index(fields=['date'], name='transaction_date_7edf95_idx'), models.Index(fields=['category'], name='transaction_categor_bf503b_idx')],
            },
        ),
    ]
