# Generated by Django 6.0.6 on 2026-07-04 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('value', models.FloatField(default=0)),
                ('calculation', models.CharField(choices=[('manual', 'Manual'), ('calculated', 'Auto-calculated'), ('derived', 'Derived')], default='manual', max_length=20)),
                ('suffix', models.CharField(default='', max_length=10)),
                ('up_is_good', models.BooleanField(default=True)),
                ('decimals', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'business_metrics',
                'unique_together': {('user', 'key')},
            },
        ),
        migrations.CreateModel(
            name='MetricHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='finance_app.businessmetric')),
            ],
            options={
                'db_table': 'metric_history',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
