# Generated by Django 6.0.6 on 2026-07-04 15:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_type', models.CharField(choices=[('TASK', 'Task'), ('MESSAGE', 'Message'), ('NOTE', 'Note'), ('IDEA', 'Idea'), ('LIBRARY', 'Library')], max_length=20)),
                ('resource_id', models.CharField(blank=True, max_length=255, null=True)),
                ('file_key', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(default=0)),
                ('mime_type', models.CharField(default='application/octet-stream', max_length=127)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'file_attachments',
                'indexes': [models.Index(fields=['user'], name='file_attach_user_id_3c252c_idx'), models.Index(fields=['resource_type', 'resource_id'], name='file_attach_resourc_e28d3b_idx')],
            },
        ),
    ]
