# Generated by Django 6.0.6 on 2026-07-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0002_sprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
